### ISSUE TITLE
Display does not work

### ISSUE THREAD

**Issue by benjamindeleener** [PolyCortex/pyMuse#5]
It seems that matplotlib is not thread safe and nothing happens when plt.show() is called.

**Comment by benjamindeleener** [comment]
Changing matplotlib backend to `TkAgg` opens the window but I got this error:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/benjamindeleener/code/pyMuse/pymuse/viz.py", line 132, in refresh
    self.axes_plot[i].set_ydata(signal_data[i, :])
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 1190, in set_ydata
    self.stale = True
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 270, in stale
    self.stale_callback(self, val)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 75, in _stale_axes_callback
    self.axes.stale = val
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 270, in stale
    self.stale_callback(self, val)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 56, in _stale_figure_callback
    self.figure.stale = val
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 270, in stale
    self.stale_callback(self, val)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 576, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 377, in draw_idle
    self._idle_callback = self._tkcanvas.after_idle(idle_draw)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 602, in after_idle
    return self.after('idle', func, *args)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 594, in after
    name = self._register(callit)
  File "/Users/benjamindeleener/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 1215, in _register
    self.tk.createcommand(name, f)
RuntimeError: main thread is not in main loop
```

**Comment by benjamindeleener** [comment]
Note that I had to reinstall matplotlib using pip to allow `TkAgg` to work with Conda.

**Comment by benjamindeleener** [comment]
The issue was that a matplotlib figure can be updated only in the same thread as it has been created. It is now fixed.
